passwordHash: ENC[AES256_GCM,data:9LLgr5DPkR5NR1OO+rLqtNVDNdYY7U/1zi4e1HN2HUnB6qRiYJAPCi+4htueif9W48nrYcMoviOrpy3lI2j1WIpMhCFLuDVRarmgj7h5Opf/UHSQAgTLw9tFVs4vknzsIU6Nkb7AcR1o9A==,iv:z9NH/idWhtiVe59syE/y0bLpez3Dl2Sclx2pBDr9Q48=,tag:4HJvhzH1bc887hjhUiKnsg==,type:str]
sops:
    age:
        - recipient: age1gsh7dq6n2zs57v9pemhymd4cynvqrwe9axf8tw9j3fhv4xl80y0qe783jk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMRXFoek9PUjFuMzVqSUNX
            ejl6OGV1SitOUzUydlptakxvQm42UzcwRWhNCmMwb1FPOU00emJPeFhuSkgraFN0
            OGllYmxJU3FkdXJ1L0EyL1V5UnJGdEUKLS0tIE5wVnNyWHlYSndhcW9FUWNGOWVB
            L1crRnBCS3pGRkFMYjNlWUxuWmFOQncKqtNIhOZPQlzol1lXVIwuHvTEDaaTC3bR
            OSRUVXupXKjkrO4vEoqaOHL0l4ScH4jQeIeZKDVn7zz+vU3EzMKYZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-30T00:31:40Z"
    mac: ENC[AES256_GCM,data:xb62zyrADKVfbVuiYshUfn5tl1Hdy+K+eTlklaT7VzbooJsbnu1fK8VHi0Sc3G2G7i4h0DdScVdIj1FSiDnkfklgT2IH4yDz99Fbee2xLd+AoQjGvO1RidM5BZUSg+F5Jxf20z4PajGzI520D03d0jzp9K8wmWrSbNYJPvMzLug=,iv:TTr1oLqooHCnmI5sHjcTWg7HaUg4pcwlh/O5Q42xK3M=,tag:nnZVZOkDawqjycD2UNs5bg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
